name: Publish NuGet Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./src/
      run: dotnet restore
    - name: Extract version from release tag
      id: extract_version
      run: |
        VERSION_PREFIX=${{ github.event.release.tag_name }}
        VERSION_PREFIX=${VERSION_PREFIX#v} # Remove 'v' prefix if present
        echo "Version: $VERSION_PREFIX"
        echo "::set-output name=VERSION_PREFIX::$VERSION_PREFIX"
    - name: Build
      working-directory: ./src/
      env:
        VERSION_PREFIX: ${{ steps.extract_version.outputs.VERSION_PREFIX }}
      run: dotnet build --configuration Release --no-restore /p:VersionPrefix=$VERSION_PREFIX
    - name: Test
      working-directory: ./src/
      run: dotnet test
    - name: Pack
      working-directory: ./src/
      env:
        VERSION_PREFIX: ${{ steps.extract_version.outputs.VERSION_PREFIX }}
      run: dotnet pack --configuration Release --no-build --output ./nupkg /p:VersionPrefix=$VERSION_PREFIX
    - uses: actions/upload-artifact@v4
      with:
        name: nuget-packagesq
        path: ./src/nupkg/*.nupkg
    # - name: Publish to NuGet
    #   working-directory: ./src/
    #   env:
    #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    #   run: dotnet nuget push ./nupkg/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
